version: "3"

services:
   database:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=javadb
        volumes:
            - pgdata:/var/lib/postgres/data
   spring:
        build: .
        restart: on-failure
        ports:
            - 8080:8080
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/javadb
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=1234
        depends_on:
            - database
       

volumes:
    pgdata:
        


